import os
import pandas as pd
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Custom canvas to generate dynamic footer 'Page X of Y' and header borders."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Colors
        navy = colors.HexColor("#0B132B")
        grey = colors.HexColor("#6B7280")
        
        # Header (Top Border and Title)
        self.setStrokeColor(navy)
        self.setLineWidth(1)
        self.line(54, 738, 558, 738)  # Margin 0.75 in (54 pt) to 8.5 in (612 pt) - 0.75 in = 558 pt
        
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(navy)
        self.drawString(54, 744, "KARNATAKA STATE POLICE - DAILY INTELLIGENCE BULLETIN")
        self.drawRightString(558, 744, "CONFIDENTIAL / INTERNAL USE ONLY")
        
        # Footer
        self.setStrokeColor(colors.HexColor("#E5E7EB"))
        self.line(54, 54, 558, 54)
        
        self.setFont("Helvetica", 8)
        self.setFillColor(grey)
        self.drawString(54, 42, f"Report Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")
        self.drawRightString(558, 42, f"Page {self._pageNumber} of {page_count}")
        
        self.restoreState()

def generate_pdf_report(df_summary, kpi_dict, leaderboard_df, predictions_list, recommendations, output_path="reports/crime_report.pdf"):
    """
    Generates a professional PDF intelligence report containing
    KPI summaries, leaderboards, predictions, and recommendations.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # 0.75 inch margins (54 points)
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=72, # extra margin for header
        bottomMargin=72 # extra margin for footer
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Palette
    navy = colors.HexColor("#0B132B")
    cyan = colors.HexColor("#00B4D8")
    dark_gray = colors.HexColor("#1F2937")
    light_bg = colors.HexColor("#F9FAFB")
    border_color = colors.HexColor("#E5E7EB")
    
    # Custom Styles
    styles.add(ParagraphStyle(
        name='DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=navy,
        spaceAfter=15
    ))
    
    styles.add(ParagraphStyle(
        name='DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=20
    ))
    
    styles.add(ParagraphStyle(
        name='SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=navy,
        spaceBefore=12,
        spaceAfter=8,
        keepWithNext=True
    ))

    styles.add(ParagraphStyle(
        name='TableText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=dark_gray
    ))

    styles.add(ParagraphStyle(
        name='TableTextBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=navy
    ))
    
    styles.add(ParagraphStyle(
        name='RecommendationText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=14,
        textColor=dark_gray,
        spaceAfter=6
    ))
    
    story = []
    
    # Title & Subtitle
    story.append(Paragraph("CRIMEVISION AI - DAILY INTELLIGENCE BULLETIN", styles['DocTitle']))
    story.append(Paragraph(
        f"Daily strategic intelligence briefing generated by CrimeVision AI. Designed for state-level patrol scheduling, active force deployment, and proactive predictive risk assessments. Analyzed dataset: {kpi_dict['total_crimes']:,} files.", 
        styles['DocSubTitle']
    ))
    
    # Section 1: Key Performance Indicators
    story.append(Paragraph("1. State Crime KPI Dashboard", styles['SectionHeader']))
    
    kpi_data = [
        [
            Paragraph("<b>Total Crime Incidents:</b>", styles['TableText']), f"{kpi_dict['total_crimes']:,}",
            Paragraph("<b>Active Cases:</b>", styles['TableText']), f"{kpi_dict['active_cases']:,}"
        ],
        [
            Paragraph("<b>Solved Cases:</b>", styles['TableText']), f"{kpi_dict['solved_cases']:,}",
            Paragraph("<b>High-Risk Incidents:</b>", styles['TableText']), f"{kpi_dict['high_risk_cases']:,}"
        ],
        [
            Paragraph("<b>Repeat Offenders Count:</b>", styles['TableText']), f"{kpi_dict['repeat_offenders']}",
            Paragraph("<b>Crime Growth Rate (60d):</b>", styles['TableText']), f"{kpi_dict['growth_percentage']}%"
        ],
        [
            Paragraph("<b>Crime Severity Index:</b>", styles['TableText']), f"{kpi_dict['crime_severity_index']}/100",
            Paragraph("<b>Investigation Solve Rate:</b>", styles['TableText']), f"{round(kpi_dict['solved_cases'] / kpi_dict['total_crimes'] * 100, 1)}%"
        ]
    ]
    
    kpi_table = Table(kpi_data, colWidths=[150, 100, 150, 104])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), light_bg),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 10),
        ('RIGHTPADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 15))
    
    # Section 2: District Leaderboards
    story.append(Paragraph("2. Top District Crime Leaderboards", styles['SectionHeader']))
    
    # Sort leaderboard to show top 5 high risk districts
    lead_sorted = leaderboard_df.sort_values(by="Risk Score", ascending=False).head(5)
    
    lead_data = [[
        Paragraph("<b>District Name</b>", styles['TableTextBold']),
        Paragraph("<b>Incident Count</b>", styles['TableTextBold']),
        Paragraph("<b>Risk Score</b>", styles['TableTextBold']),
        Paragraph("<b>Growth Rate</b>", styles['TableTextBold']),
        Paragraph("<b>Severity Index</b>", styles['TableTextBold'])
    ]]
    
    for _, row in lead_sorted.iterrows():
        lead_data.append([
            Paragraph(str(row["District"]), styles['TableText']),
            Paragraph(f"{row['Crime Count']:,}", styles['TableText']),
            Paragraph(f"{row['Risk Score']}/100", styles['TableText']),
            Paragraph(f"{row['Crime Growth Rate (%)']}%", styles['TableText']),
            Paragraph(f"{row['Severity Index']}/100", styles['TableText'])
        ])
        
    lead_table = Table(lead_data, colWidths=[140, 90, 90, 90, 94])
    lead_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, light_bg]),
    ]))
    story.append(lead_table)
    story.append(Spacer(1, 15))
    
    # Section 3: Predictive Volume Insights
    story.append(Paragraph("3. Future Volume Projections", styles['SectionHeader']))
    
    pred_headers = [[
        Paragraph("<b>Target District</b>", styles['TableTextBold']),
        Paragraph("<b>Crime Category</b>", styles['TableTextBold']),
        Paragraph("<b>Current Monthly Avg</b>", styles['TableTextBold']),
        Paragraph("<b>Next Month Projection</b>", styles['TableTextBold']),
        Paragraph("<b>Predicted Trend</b>", styles['TableTextBold'])
    ]]
    
    for p in predictions_list[:5]: # show top 5 projections
        # compute trend arrow
        trend = "INCREASE" if p['predicted'] > p['current'] else "DECREASE"
        color_code = "#DC2626" if trend == "INCREASE" else "#16A34A"
        
        pred_headers.append([
            Paragraph(p['district'], styles['TableText']),
            Paragraph(p['category'], styles['TableText']),
            Paragraph(f"{p['current']:.1f}", styles['TableText']),
            Paragraph(f"{p['predicted']:.1f}", styles['TableText']),
            Paragraph(f"<font color='{color_code}'><b>{trend}</b></font>", styles['TableText'])
        ])
        
    pred_table = Table(pred_headers, colWidths=[140, 110, 100, 100, 54])
    pred_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('GRID', (0,0), (-1,-1), 0.5, border_color),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, light_bg]),
    ]))
    story.append(pred_table)
    
    # Force page break for recommendations and strategic overview
    story.append(PageBreak())
    
    # Section 4: Strategic Recommendations
    story.append(Paragraph("4. Strategic Intelligence Recommendations", styles['SectionHeader']))
    
    for i, rec in enumerate(recommendations, 1):
        rec_title = rec.split(":")[0] if ":" in rec else f"Recommendation {i}"
        rec_desc = rec.split(":")[1] if ":" in rec else rec
        
        story.append(Paragraph(f"<b>{i}. {rec_title}:</b>", styles['TableTextBold']))
        story.append(Paragraph(rec_desc.strip(), styles['RecommendationText']))
        story.append(Spacer(1, 8))
        
    story.append(Spacer(1, 15))
    
    # Disclaimer note
    story.append(Paragraph("<b>System Notice & Disclaimer:</b>", styles['TableTextBold']))
    story.append(Paragraph(
        "CrimeVision AI is an assistive decision support platform. Predictive indicators, risk scores, "
        "and relationship graphs are mathematical outputs computed from historical incident inputs. "
        "All data and insights should be cross-referenced with human field intelligence. "
        "This is confidential material and must not be distributed to unauthorized personnel.",
        styles['RecommendationText']
    ))
    
    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"PDF successfully generated at '{output_path}'.")
    return output_path
